name: Auto-format with autopep8

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types:
      - ready_for_review
      - review_requested

jobs:
  autopep8:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@va81bbbf8298c0fa03ea29cdc473d45769f953675
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install autopep8
        run: pip install autopep8
      - name: Run autopep8
        run: autopep8 --in-place --recursive .
